//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Negocios2017Entities1 : DbContext
    {
        public Negocios2017Entities1()
            : base("name=Negocios2017Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_clientes> tb_clientes { get; set; }
        public DbSet<tb_paises> tb_paises { get; set; }
    
        public virtual int USP_ACTUALIZAR_CLIENTES(string iD, string nOM, string dIR, string iDP, string tEL)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var dIRParameter = dIR != null ?
                new ObjectParameter("DIR", dIR) :
                new ObjectParameter("DIR", typeof(string));
    
            var iDPParameter = iDP != null ?
                new ObjectParameter("IDP", iDP) :
                new ObjectParameter("IDP", typeof(string));
    
            var tELParameter = tEL != null ?
                new ObjectParameter("TEL", tEL) :
                new ObjectParameter("TEL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_ACTUALIZAR_CLIENTES", iDParameter, nOMParameter, dIRParameter, iDPParameter, tELParameter);
        }
    
        public virtual int USP_CREAR_CLIENTES(string iD, string nOM, string dIR, string iDP, string tEL)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var dIRParameter = dIR != null ?
                new ObjectParameter("DIR", dIR) :
                new ObjectParameter("DIR", typeof(string));
    
            var iDPParameter = iDP != null ?
                new ObjectParameter("IDP", iDP) :
                new ObjectParameter("IDP", typeof(string));
    
            var tELParameter = tEL != null ?
                new ObjectParameter("TEL", tEL) :
                new ObjectParameter("TEL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_CREAR_CLIENTES", iDParameter, nOMParameter, dIRParameter, iDPParameter, tELParameter);
        }
    
        public virtual int USP_ELIMINAR_CLIENTES(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_ELIMINAR_CLIENTES", iDParameter);
        }
    
        public virtual ObjectResult<USP_LISTAR_CLIENTES_Result> USP_LISTAR_CLIENTES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_LISTAR_CLIENTES_Result>("USP_LISTAR_CLIENTES");
        }
    
        public virtual ObjectResult<USP_LISTAR_PAIS_Result> USP_LISTAR_PAIS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_LISTAR_PAIS_Result>("USP_LISTAR_PAIS");
        }
    }
}
